# AUTOGENERATED from openapi.json by bin/codegen.sh — do not edit.
# ruff: noqa

from typing import Any, Literal, NotRequired, TypedDict



class APNPostModel(TypedDict):
    token: str
    data: dict[str, Any]
    bundle_id: NotRequired[str]



class AppleLoginPostHandler(TypedDict):
    token: str
    lang: NotRequired[str | None]



class ApplePOSTResp(TypedDict):
    apple_id: str



class AppleWorkoutType(TypedDict):
    apple_code: int
    name: str
    name_fr: str



class BaseGroupItem(TypedDict):
    nb_reps: int
    skip_last: bool
    id: str
    name: NotRequired[str | None]
    position: int
    description: NotRequired[str | None]
    duration: NotRequired[int | None]



class BodyUploadAFitFileAndCreateASessionForItV1ThirdPartyFitUploadPost(TypedDict):
    source: Literal['zwift']
    md5: str
    path: str
    size: int
    name: NotRequired[str | None]



class BodyUploadNewMediaV1MediaDataTypeUploadPost(TypedDict):
    content_type: str
    md5: str
    path: str
    size: int
    width: int
    height: int
    name: NotRequired[str | None]
    mime_type: NotRequired[str | None]
    session_id: NotRequired[str | None]
    id: NotRequired[str | None]



class CountryItem(TypedDict):
    code_iso_2: str
    code_iso_3: str
    country: str



class CreateTokenReq(TypedDict):
    description: NotRequired[str | None]
    expires_at: NotRequired[str | None]



class DeleteSessionsResp(TypedDict):
    status: str
    ids: list[str]



class DeviceApproveReq(TypedDict):
    user_code: str
    expires_at: NotRequired[str | None]



class DeviceApproveResp(TypedDict):
    description: str | None



class DeviceInfos(TypedDict):
    os: str
    os_version: str
    system_name: str



class DeviceInitReq(TypedDict):
    description: NotRequired[str | None]



class DeviceInitResp(TypedDict):
    device_code: str
    user_code: str
    expires_in: int
    interval: int



class DeviceLookupResp(TypedDict):
    description: str | None
    expires_in: int



class DeviceTokenReq(TypedDict):
    device_code: str



class DeviceTokenResp(TypedDict):
    token: str
    description: str | None
    created_at: str



type DistanceSystem = Literal[0, 1]



class EquipmentPostResp(TypedDict):
    id: str



class ExerciseGroupModel(TypedDict):
    id: NotRequired[str | None]
    nb_reps: NotRequired[int | None]
    skip_last: NotRequired[bool | None]
    name: NotRequired[str | None]
    description: NotRequired[str | None]
    duration: NotRequired[int | None]
    duration_real: NotRequired[int | None]



class ExerciseNameGetResp(TypedDict):
    name_taken: bool



class ExercisePostResp(TypedDict):
    id: str



class FCMPostModel(TypedDict):
    data: dict[str, Any]



class FacebookLoginPostHandler(TypedDict):
    token: str
    lang: NotRequired[str | None]



class FeedbackPost(TypedDict):
    category: str
    message: str
    context: NotRequired[str | None]



class FitFilesPostResp(TypedDict):
    status: str
    session_id: str



class ForgotPwdResp(TypedDict):
    status: str



class FriendItem(TypedDict):
    username: str
    created_at: str
    avatar: NotRequired[str | None]
    status: str



class FriendPostModel(TypedDict):
    username: str



class FriendRequestPatchModel(TypedDict):
    username: str
    status: Literal['accepted', 'refused']



class FriendSuggested(TypedDict):
    username: str
    avatar: NotRequired[str | None]



class FriendSuggestionsResp(TypedDict):
    suggested: list[FriendSuggested]



class FriendsResp(TypedDict):
    friends: list[FriendItem]



class GarminAuthResp(TypedDict):
    url: str



type GenderType = Literal[0, 1, 2]



class GeoBoundaries(TypedDict):
    ne: list[float]
    sw: list[float]



class GetUsersBody(TypedDict):
    prefix: int



class GetUsersResp(TypedDict):
    deleted: int
    created: int



class GoogleLoginPostHandler(TypedDict):
    token: str
    lang: NotRequired[str | None]



class GroupLeavePOSTModel(TypedDict):
    id: str



class GroupRequestPatchModel(TypedDict):
    id: str
    name: NotRequired[str | None]



class GroupRequestPostModel(TypedDict):
    name: str
    users: list[str]



class GroupSessionsPostModel(TypedDict):
    id: str
    session_ids: list[str]



class GroupSessionsTransferModel(TypedDict):
    group_id: str
    to_user: str
    session_ids: list[str]



class GroupUserPostModel(TypedDict):
    id: str
    users: list[str]



class HRZone(TypedDict):
    duration: int
    hr_max: NotRequired[int | None]
    hr_min: NotRequired[int | None]



class HRZoneModel(TypedDict):
    zone: int
    hr_min: int
    hr_max: int



class HealthItem(TypedDict):
    up: NotRequired[bool]



class ImageItem(TypedDict):
    path: str
    file_type: str
    width: int
    height: int
    id: str



class LapItem(TypedDict):
    lap_index: int
    ts_start: int
    ts_end: NotRequired[int | None]
    total_timer_time: NotRequired[float | None]
    total_elapsed_time: NotRequired[float | None]
    total_moving_time: NotRequired[float | None]
    distance: NotRequired[float | None]
    bpm_avg: NotRequired[int | None]
    bpm_max: NotRequired[int | None]
    speed_avg: NotRequired[float | None]
    speed_max: NotRequired[float | None]
    cadence_avg: NotRequired[int | None]
    cadence_max: NotRequired[int | None]
    power_avg: NotRequired[int | None]
    power_max: NotRequired[int | None]
    total_strokes: NotRequired[int | None]
    lap_trigger: NotRequired[str | None]



class LoginPostHandler(TypedDict):
    email: NotRequired[str | None]
    username: NotRequired[str | None]
    password: str



class LoginTokenPostModel(TypedDict):
    token: str



class LoginWithAppleResp(TypedDict):
    status: str
    is_new_user: NotRequired[bool | None]



class LoginWithFacebookResp(TypedDict):
    status: str
    is_new_user: NotRequired[bool | None]



class LoginWithGoogleResp(TypedDict):
    status: str
    is_new_user: NotRequired[bool | None]



class LoginWithTokenResp(TypedDict):
    status: str



class LogoutPostHandler(TypedDict):
    refresh_token: str



class LogoutResp(TypedDict):
    status: str



class MasterTokenBody(TypedDict):
    user_id: NotRequired[str | None]
    email: NotRequired[str | None]



class MasterTokenResp(TypedDict):
    access_token: str
    token_type: Literal['bearer']
    expires_in: int



class MeasurementItem(TypedDict):
    date: str
    weight: float



class MeasurementPostModel(TypedDict):
    date: str
    height: NotRequired[float | str | None]
    weight: NotRequired[float | str | None]
    body_fat: NotRequired[float | str | None]
    chest: NotRequired[float | str | None]
    waist: NotRequired[float | str | None]
    shoulders: NotRequired[float | str | None]
    hips: NotRequired[float | str | None]
    buttocks: NotRequired[float | str | None]
    notes: NotRequired[str | None]
    biceps: NotRequired[tuple[float | str | None, float | str | None] | None]
    forearms: NotRequired[tuple[float | str | None, float | str | None] | None]
    calves: NotRequired[tuple[float | str | None, float | str | None] | None]
    thighs: NotRequired[tuple[float | str | None, float | str | None] | None]
    knees: NotRequired[tuple[float | str | None, float | str | None] | None]



class MergeSessionsPOST(TypedDict):
    session_from: str
    session_to: str



class MetricItem(TypedDict):
    pass



class MetricAnnotatedFloatAnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0AnnotatedFloatAnnotatedUnionIntFloatNoneTypeAfterValidator(TypedDict):
    real: float | None
    objective: float | None



class MetricAnnotatedIntAnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0AnnotatedIntAnnotatedUnionIntFloatNoneTypeAfterValidator(TypedDict):
    real: int | None
    objective: int | None



class MetricDictDict(TypedDict):
    real: dict[str, Any] | None
    objective: dict[str, Any] | None



class MetricFloatFloat(TypedDict):
    real: float | None
    objective: float | None



class MetricIntInt(TypedDict):
    real: int | None
    objective: int | None



class MetricTupleAnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0AnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0TupleAnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0AnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0(TypedDict):
    real: tuple[int | float | None, int | float | None] | None
    objective: tuple[int | float | None, int | float | None] | None



class MinMaxFieldFloat(TypedDict):
    v_min: NotRequired[float | None]
    v_max: NotRequired[float | None]



class MinMaxFieldInt(TypedDict):
    v_min: NotRequired[int | None]
    v_max: NotRequired[int | None]



class MostSearchedItem(TypedDict):
    text: str
    count: int



class MuscleItem(TypedDict):
    id: int
    icon: str | None
    body_part: str
    muscle_group: str



class NotificationToken(TypedDict):
    token: str
    device_infos: DeviceInfos



type Objective = Literal[0, 1, 2]



class PolarAuthResp(TypedDict):
    url: str



class PostMediaResp(TypedDict):
    status: str
    id: str
    path: str
    thumbnail: NotRequired[str | None]



class PostSessionResp(TypedDict):
    id: str



class PowerZoneModel(TypedDict):
    zone: int
    power_min: int
    power_max: int



class PreviousSearchedItem(TypedDict):
    text: str
    last_searched: str



type ProfileType = Literal[0, 1, 2]



class QuotaLimit(TypedDict):
    current: int
    limit: int



class Quotas(TypedDict):
    exercises: QuotaLimit
    groups: QuotaLimit



class RefreshPostHandler(TypedDict):
    refresh_token: str



class RegisterResp(TypedDict):
    status: str



class RequirementItem(TypedDict):
    exercise_id: str
    requirement_id: str



class SampleItem(TypedDict):
    ts: int
    heart_rate: NotRequired[int | None]
    temperature: NotRequired[int | None]
    cadence: NotRequired[int | None]
    power: NotRequired[int | None]
    speed: NotRequired[float | None]
    elevation: NotRequired[int | None]
    distance: NotRequired[float | None]
    location: NotRequired[list[float] | None]



class SearchEquipmentItem(TypedDict):
    id: str
    name: str
    username: str



class SearchEquipmentsResp(TypedDict):
    results: list[SearchEquipmentItem | str]



class SearchInfosPost(TypedDict):
    search_text: str



class SearchInfosResp(TypedDict):
    most_searched: list[MostSearchedItem]
    last_searched: list[PreviousSearchedItem]



class SessionGeo(TypedDict):
    boundaries: GeoBoundaries
    geojson: dict[str, Any]



class Side(TypedDict):
    left: float | None
    right: float | None



type SpeedUnit = Literal['km/h', 'min/km', 'min/100m', 'min/500m', 'mph']



class SportItem(TypedDict):
    calories: int
    distance: float
    duration: int
    icon: str
    nb_sessions: int
    sport: str | None



class SportMetricsResp(TypedDict):
    default: list[str]
    overrides: dict[str, list[str]]



class SportProfileItem(TypedDict):
    id: int
    name: str
    ftp: int | None
    pool_length: float | None
    is_default: bool
    sport_ids: list[int]
    hr_zones: list[HRZoneModel]
    power_zones: list[PowerZoneModel]



class SportProfilePatchModel(TypedDict):
    id: int
    name: NotRequired[str | None]
    ftp: NotRequired[int | None]
    pool_length: NotRequired[float | None]
    is_default: NotRequired[bool | None]
    sport_ids: NotRequired[list[int] | None]
    hr_zones: NotRequired[list[HRZoneModel] | None]
    power_zones: NotRequired[list[PowerZoneModel] | None]



class SportProfilePostModel(TypedDict):
    name: str
    ftp: NotRequired[int | None]
    pool_length: NotRequired[float | None]
    is_default: NotRequired[bool]
    sport_ids: NotRequired[list[int]]
    hr_zones: NotRequired[list[HRZoneModel]]
    power_zones: NotRequired[list[PowerZoneModel]]



class SportProfilePostResp(TypedDict):
    id: int



class StatusResp(TypedDict):
    status: str



class SuuntoAuthResp(TypedDict):
    url: str



class TagItem(TypedDict):
    label: str
    data_type: str



type TemperatureSystem = Literal[0, 1]



class TemplateExerciseItemPost(TypedDict):
    exercise_id: str
    side: NotRequired[Literal['left', 'right'] | None]
    speed_unit: NotRequired[SpeedUnit | None]
    group_position: NotRequired[int | None]
    bpm: NotRequired[tuple[int, int] | None]
    vo2max: NotRequired[tuple[int, int] | None]
    distance: NotRequired[float | None]
    speed: NotRequired[float | None]
    duration: NotRequired[int | None]
    climb: NotRequired[int | None]
    descent: NotRequired[int | None]
    nb_reps: NotRequired[int | None]
    weight: NotRequired[float | None]
    power: NotRequired[int | None]
    cadence: NotRequired[float | None]
    others: NotRequired[dict[str, Any] | None]



class TemplateGroupItemPost(TypedDict):
    id: NotRequired[str | None]
    nb_reps: NotRequired[int | None]
    skip_last: NotRequired[bool | None]
    name: NotRequired[str | None]
    description: NotRequired[str | None]
    duration: NotRequired[int | None]



class TemplateMetricItem(TypedDict):
    pass



class TemplatePostResp(TypedDict):
    id: str



class ThirdPartyLoginResp(TypedDict):
    access_token: str
    token_type: Literal['bearer']
    refresh_token: str
    refresh_expires_at: str
    is_new_user: NotRequired[bool | None]



type ThirdPartyStatus = Literal[0, 1, 2]



class ThumbnailItem(TypedDict):
    path: str
    file_type: str
    width: int
    height: int



class TokenCreatedResp(TypedDict):
    id: int
    token: str
    description: str | None
    expires_at: str | None
    created_at: str



class TokenResp(TypedDict):
    id: int
    description: str | None
    expires_at: str | None
    created_at: str



type TrainingStatus = Literal[0, 1]



class UrlItem(TypedDict):
    id: str
    url: str



class UserPatchResp(TypedDict):
    status: str
    fields: NotRequired[dict[str, Any] | None]



class ValidationError(TypedDict):
    loc: list[str | int]
    msg: str
    type: str
    input: NotRequired[Any]
    ctx: NotRequired[dict[str, Any]]



class VersionItem(TypedDict):
    version: str



class VideoItem(TypedDict):
    id: str
    path: str
    file_type: str
    width: int
    height: int
    thumbnails: list[ThumbnailItem]



type VisibilityType = Literal[0, 1, 2]



type WeightSystem = Literal[0, 1]



class WithingsAuthUrlResp(TypedDict):
    url: str



class ApiRoutersAuth2UtilsLoginResp(TypedDict):
    access_token: str
    token_type: Literal['bearer']
    refresh_token: str
    refresh_expires_at: str



class ApiRoutersAuthLoginLoginResp(TypedDict):
    status: str



class ApiRoutersGroupsGroupsGroupItem(TypedDict):
    id: str
    name: str
    is_admin: bool



class ApiRoutersGroupsGroupsUserItem(TypedDict):
    username: str
    is_admin: bool
    avatar: NotRequired[str | None]



class ApiRoutersSearchUsersUserItem(TypedDict):
    username: str
    avatar: NotRequired[str | None]



class ApiRoutersTrainingExercisesExerciseExerciseItem(TypedDict):
    id: str
    name: str
    description: NotRequired[str | None]
    visibility: VisibilityType
    favorite: bool
    medias: list[VideoItem | ImageItem | UrlItem]
    equipments: list[str]
    requirements: list[RequirementItem]
    tags: list[str]
    muscles: list[int]
    nb_stars: int
    icon: NotRequired[str | None]
    username: str
    can_edit: bool
    source: str



class ApiRoutersTrainingSessionModelsExerciseItem(TypedDict):
    id: str
    name: str
    icon: NotRequired[str | None]
    media: NotRequired[VideoItem | ImageItem | UrlItem | None]
    can_edit: bool



class ApiRoutersTrainingSessionModelsGroupItem(TypedDict):
    nb_reps: int
    skip_last: bool
    id: str
    name: NotRequired[str | None]
    position: int
    description: NotRequired[str | None]
    duration: NotRequired[int | None]
    duration_real: NotRequired[int | None]



class ActivityItem(TypedDict):
    id: str
    ts_start: str
    ts_end: str | None
    visibility: VisibilityType
    notes: str | None
    icon: str
    name: str | None
    nb_exercises: int
    tags: list[str]
    calories: int | None
    distance: float | None
    climb: float | None
    descent: float | None
    source: str
    synced: list[dict[str, Any]]
    bpm_avg: int | None
    bpm_max: int | None
    cadence_avg: int | None
    cadence_max: int | None
    power_avg: int | None
    power_max: int | None
    speed_avg: float | None
    speed_max: float | None
    device_name: NotRequired[str | None]
    can_edit: bool
    username: str
    avatar: str | None
    map: str | None



class ActivityStatItem(TypedDict):
    date: str
    sports: list[SportItem]
    calories: int | None
    steps: int | None



class CountriesResp(TypedDict):
    countries: list[CountryItem]



class EquipmentItem(TypedDict):
    id: str
    name: str
    visibility: VisibilityType
    medias: list[VideoItem | ImageItem | UrlItem]
    username: str
    can_edit: bool
    source: Literal['user', 'friend']



class EquipmentPatchModel(TypedDict):
    visibility: NotRequired[VisibilityType | None]
    id: str
    name: NotRequired[str | None]



class EquipmentPostModel(TypedDict):
    visibility: NotRequired[VisibilityType | None]
    name: str



class ExercisePatchModel(TypedDict):
    description: NotRequired[str | None]
    url: NotRequired[str | None]
    favorite: NotRequired[bool | None]
    visibility: NotRequired[VisibilityType | None]
    tags: NotRequired[list[str] | None]
    equipments: NotRequired[list[str] | None]
    requirements: NotRequired[list[str] | None]
    muscles: NotRequired[list[int] | None]
    icon: NotRequired[str | None]
    id: str
    name: NotRequired[str | None]



class ExercisePostModel(TypedDict):
    description: NotRequired[str | None]
    url: NotRequired[str | None]
    favorite: NotRequired[bool | None]
    visibility: NotRequired[VisibilityType | None]
    tags: NotRequired[list[str] | None]
    equipments: NotRequired[list[str] | None]
    requirements: NotRequired[list[str] | None]
    muscles: NotRequired[list[int] | None]
    icon: NotRequired[str | None]
    name: str



class GroupItemLite(TypedDict):
    id: str
    name: str
    users: list[ApiRoutersGroupsGroupsUserItem]



class GroupItemSummary(TypedDict):
    id: str
    name: str
    is_admin: bool
    users: list[ApiRoutersGroupsGroupsUserItem]
    nb_sessions: int



class GroupSessionItem(TypedDict):
    id: str
    notes: NotRequired[str | None]
    name: NotRequired[str | None]
    visibility: NotRequired[VisibilityType | None]
    ts_start: NotRequired[str | None]
    ts_end: NotRequired[str | None]
    tags: NotRequired[list[str] | None]
    calories: NotRequired[int | None]
    distance: NotRequired[float | None]
    climb: NotRequired[float | None]
    descent: NotRequired[float | None]
    bpm_avg: NotRequired[int | None]
    bpm_max: NotRequired[int | None]
    cadence_avg: NotRequired[int | None]
    cadence_max: NotRequired[int | None]
    power_avg: NotRequired[int | None]
    power_max: NotRequired[int | None]
    speed_avg: NotRequired[float | None]
    speed_max: NotRequired[float | None]
    pool_length: NotRequired[float | None]
    has_laps: NotRequired[bool]
    nb_exercises: int
    status: NotRequired[TrainingStatus]
    username: str
    synced: list[dict[str, Any]]
    source: str
    device_name: NotRequired[str | None]
    can_edit: bool
    icon: str
    created_by: NotRequired[str | None]



class HTTPValidationError(TypedDict):
    detail: NotRequired[list[ValidationError]]



class LoadActivitiesResp(TypedDict):
    offset: int
    activities: list[ActivityItem]



class MeasurementLight(TypedDict):
    weight: NotRequired[float | None]
    body_fat: NotRequired[float | None]
    chest: NotRequired[float | None]
    waist: NotRequired[float | None]
    shoulders: NotRequired[float | None]
    hips: NotRequired[float | None]
    buttocks: NotRequired[float | None]
    biceps: NotRequired[Side | None]
    forearms: NotRequired[Side | None]
    calves: NotRequired[Side | None]
    thighs: NotRequired[Side | None]
    knees: NotRequired[Side | None]



class MetricMinMaxFieldFloatMinMaxFieldFloat(TypedDict):
    real: MinMaxFieldFloat | None
    objective: MinMaxFieldFloat | None



class MetricMinMaxFieldIntMinMaxFieldInt(TypedDict):
    real: MinMaxFieldInt | None
    objective: MinMaxFieldInt | None



class PreviousMeasurements(TypedDict):
    weight: NotRequired[float | None]
    body_fat: NotRequired[float | None]
    chest: NotRequired[float | None]
    waist: NotRequired[float | None]
    shoulders: NotRequired[float | None]
    hips: NotRequired[float | None]
    buttocks: NotRequired[float | None]
    biceps: NotRequired[Side | None]
    forearms: NotRequired[Side | None]
    calves: NotRequired[Side | None]
    thighs: NotRequired[Side | None]
    knees: NotRequired[Side | None]



class RegisterData(TypedDict):
    email: str
    username: str
    tz: NotRequired[str | None]
    lang: NotRequired[str | None]
    country: NotRequired[str | None]
    password: str
    distance_system: NotRequired[DistanceSystem]
    temp_system: NotRequired[TemperatureSystem]



class SearchExerciseItem(TypedDict):
    id: str
    name: str
    description: NotRequired[str | None]
    visibility: VisibilityType
    favorite: bool
    tags: list[str]
    equipments: list[str]
    muscles: list[int]
    nb_stars: int
    medias: list[VideoItem | ImageItem | UrlItem]
    source: str
    username: str
    can_edit: bool



class SearchExercisesResp(TypedDict):
    results: list[SearchExerciseItem | str]



class SearchSessionItem(TypedDict):
    id: str
    ts_start: str
    ts_end: NotRequired[str | None]
    visibility: VisibilityType
    notes: NotRequired[str | None]
    icon: NotRequired[str | None]
    name: NotRequired[str | None]
    tags: list[str]
    calories: NotRequired[int | None]
    distance: NotRequired[float | None]
    climb: NotRequired[float | None]
    descent: NotRequired[float | None]
    source: NotRequired[str | None]
    bpm_avg: NotRequired[int | None]
    bpm_max: NotRequired[int | None]
    cadence_avg: NotRequired[int | None]
    cadence_max: NotRequired[int | None]
    power_avg: NotRequired[int | None]
    power_max: NotRequired[int | None]
    speed_avg: NotRequired[float | None]
    speed_max: NotRequired[float | None]
    nb_exercises: int
    synced: list[dict[str, Any]]
    username: str
    created_by: NotRequired[str | None]
    status: TrainingStatus



class SearchSessionResp(TypedDict):
    results: list[SearchSessionItem | str]



class SearchTagsResp(TypedDict):
    results: list[TagItem]



class SearchTemplateItem(TypedDict):
    id: str
    name: str
    notes: NotRequired[str | None]
    visibility: VisibilityType
    tags: list[str]
    username: str
    can_edit: bool



class SearchTemplatesResp(TypedDict):
    results: list[SearchTemplateItem | str]



class SessionExerciseModel(TypedDict):
    exercise_id: str
    side: NotRequired[Literal['left', 'right'] | None]
    speed_unit: NotRequired[SpeedUnit | None]
    group_position: NotRequired[int | None]
    bpm: NotRequired[MetricTupleAnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0AnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0TupleAnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0AnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0 | None]
    vo2max: NotRequired[MetricTupleAnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0AnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0TupleAnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0AnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0 | None]
    distance: NotRequired[MetricAnnotatedFloatAnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0AnnotatedFloatAnnotatedUnionIntFloatNoneTypeAfterValidator | None]
    speed: NotRequired[MetricAnnotatedFloatAnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0AnnotatedFloatAnnotatedUnionIntFloatNoneTypeAfterValidator | None]
    duration: NotRequired[MetricAnnotatedIntAnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0AnnotatedIntAnnotatedUnionIntFloatNoneTypeAfterValidator | None]
    climb: NotRequired[MetricAnnotatedIntAnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0AnnotatedIntAnnotatedUnionIntFloatNoneTypeAfterValidator | None]
    descent: NotRequired[MetricAnnotatedIntAnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0AnnotatedIntAnnotatedUnionIntFloatNoneTypeAfterValidator | None]
    nb_reps: NotRequired[MetricAnnotatedIntAnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0AnnotatedIntAnnotatedUnionIntFloatNoneTypeAfterValidator | None]
    weight: NotRequired[MetricAnnotatedFloatAnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0AnnotatedFloatAnnotatedUnionIntFloatNoneTypeAfterValidator | None]
    power: NotRequired[MetricAnnotatedIntAnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0AnnotatedIntAnnotatedUnionIntFloatNoneTypeAfterValidator | None]
    cadence: NotRequired[MetricAnnotatedFloatAnnotatedUnionIntFloatNoneTypeFieldInfoAnnotationNoneTypeRequiredTrueMetadataGeGe0AnnotatedFloatAnnotatedUnionIntFloatNoneTypeAfterValidator | None]
    others: NotRequired[MetricDictDict | None]



class SessionItem(TypedDict):
    id: str
    notes: NotRequired[str | None]
    name: NotRequired[str | None]
    visibility: NotRequired[VisibilityType | None]
    ts_start: NotRequired[str | None]
    ts_end: NotRequired[str | None]
    tags: NotRequired[list[str] | None]
    calories: NotRequired[int | None]
    distance: NotRequired[float | None]
    climb: NotRequired[float | None]
    descent: NotRequired[float | None]
    bpm_avg: NotRequired[int | None]
    bpm_max: NotRequired[int | None]
    cadence_avg: NotRequired[int | None]
    cadence_max: NotRequired[int | None]
    power_avg: NotRequired[int | None]
    power_max: NotRequired[int | None]
    speed_avg: NotRequired[float | None]
    speed_max: NotRequired[float | None]
    pool_length: NotRequired[float | None]
    has_laps: NotRequired[bool]
    nb_exercises: int
    status: NotRequired[TrainingStatus]
    username: str
    synced: list[dict[str, Any]]
    source: str
    device_name: NotRequired[str | None]
    can_edit: bool
    icon: str



class SessionModel(TypedDict):
    notes: NotRequired[str | None]
    name: NotRequired[str | None]
    visibility: NotRequired[VisibilityType | None]
    ts_start: NotRequired[str | None]
    ts_end: NotRequired[str | None]
    tz: NotRequired[str | None]
    tags: NotRequired[list[str] | None]
    groups: NotRequired[list[ExerciseGroupModel] | None]
    calories: NotRequired[int | None]
    bpm: NotRequired[int | None]
    distance: NotRequired[float | None]
    climb: NotRequired[int | None]
    descent: NotRequired[float | None]
    bpm_avg: NotRequired[int | None]
    bpm_max: NotRequired[int | None]
    cadence_avg: NotRequired[int | None]
    cadence_max: NotRequired[int | None]
    power_avg: NotRequired[int | None]
    power_max: NotRequired[int | None]
    speed_avg: NotRequired[float | None]
    speed_max: NotRequired[float | None]
    pool_length: NotRequired[float | None]
    duplicate: NotRequired[bool]
    lang: NotRequired[str]
    status: NotRequired[TrainingStatus]
    exercises: list[SessionExerciseModel]



class SessionResp(TypedDict):
    id: str
    ts_start: str
    ts_end: str | None
    visibility: VisibilityType
    notes: str | None
    icon: str | None
    name: str | None
    tags: list[str]
    calories: int | None
    distance: float | None
    climb: float | None
    descent: float | None
    source: str | None
    bpm_avg: int | None
    bpm_max: int | None
    cadence_avg: int | None
    cadence_max: int | None
    power_avg: int | None
    power_max: int | None
    speed_avg: float | None
    speed_max: float | None
    pool_length: float | None
    has_laps: NotRequired[bool]
    heart_zones: list[HRZone]
    device_name: str | None
    sport_id: int | None
    can_edit: bool
    geo: SessionGeo | None
    exercises: list[ApiRoutersTrainingSessionModelsExerciseItem]
    groups: list[ApiRoutersTrainingSessionModelsGroupItem]
    metrics: list[MetricItem]
    status: TrainingStatus



class Stats(TypedDict):
    last: MeasurementLight | None



class TemplatePatchModel(TypedDict):
    notes: NotRequired[str | None]
    visibility: NotRequired[VisibilityType | None]
    exercises: NotRequired[list[TemplateExerciseItemPost] | None]
    groups: NotRequired[list[TemplateGroupItemPost] | None]
    tags: NotRequired[list[str] | None]
    id: str
    name: NotRequired[str | None]



class TemplatePostModel(TypedDict):
    notes: NotRequired[str | None]
    visibility: NotRequired[VisibilityType | None]
    exercises: NotRequired[list[TemplateExerciseItemPost] | None]
    groups: NotRequired[list[TemplateGroupItemPost] | None]
    tags: NotRequired[list[str] | None]
    name: str



class TokenListResp(TypedDict):
    tokens: list[TokenResp]



class TrainingTemplateGETModel(TypedDict):
    id: str
    username: str
    name: str
    visibility: VisibilityType
    exercises: list[ApiRoutersTrainingSessionModelsExerciseItem]
    groups: list[BaseGroupItem]
    metrics: list[TemplateMetricItem]
    can_edit: bool
    notes: str | None
    tags: list[str]
    icon: str



class UserData(TypedDict):
    email: NotRequired[str | None]
    username: NotRequired[str | None]
    tz: NotRequired[str | None]
    lang: NotRequired[str | None]
    password: NotRequired[str | None]
    distance_system: NotRequired[DistanceSystem | None]
    temp_system: NotRequired[TemperatureSystem | None]
    country: NotRequired[str | None]
    gender: NotRequired[GenderType | None]
    visibility: NotRequired[ProfileType | None]
    weight_system: NotRequired[WeightSystem | None]
    birthdate: NotRequired[str | None]
    objective: NotRequired[Objective | None]



class UserResp(TypedDict):
    email: str
    username: str
    country: NotRequired[str | None]
    visibility: ProfileType
    distance_system: DistanceSystem
    weight_system: WeightSystem
    temp_system: TemperatureSystem
    tz: NotRequired[str | None]
    lang: NotRequired[str | None]
    birthdate: NotRequired[str | None]
    gender: NotRequired[GenderType | None]
    objective: NotRequired[Objective | None]
    verified: bool
    avatar: NotRequired[str | None]
    polar_status: ThirdPartyStatus
    withings_status: ThirdPartyStatus
    garmin_status: ThirdPartyStatus
    suunto_status: ThirdPartyStatus
    quotas: Quotas



class CreateGroupResp(TypedDict):
    status: str
    group: GroupItemLite



class GroupResp(TypedDict):
    group: NotRequired[ApiRoutersGroupsGroupsGroupItem | None]
    sessions: NotRequired[list[GroupSessionItem] | None]
    users: NotRequired[list[ApiRoutersGroupsGroupsUserItem] | None]



class MeasurementResp(TypedDict):
    weight: NotRequired[float | None]
    body_fat: NotRequired[float | None]
    chest: NotRequired[float | None]
    waist: NotRequired[float | None]
    shoulders: NotRequired[float | None]
    hips: NotRequired[float | None]
    buttocks: NotRequired[float | None]
    biceps: NotRequired[Side | None]
    forearms: NotRequired[Side | None]
    calves: NotRequired[Side | None]
    thighs: NotRequired[Side | None]
    knees: NotRequired[Side | None]
    date: str
    previous: PreviousMeasurements
    notes: NotRequired[str | None]



class MeasurementStats(TypedDict):
    stats: Stats



class PatchMeasurementResp(TypedDict):
    measurement: MeasurementResp



class PatchSessionModel(TypedDict):
    notes: NotRequired[str | None]
    name: NotRequired[str | None]
    visibility: NotRequired[VisibilityType | None]
    ts_start: NotRequired[str | None]
    ts_end: NotRequired[str | None]
    tz: NotRequired[str | None]
    tags: NotRequired[list[str] | None]
    groups: NotRequired[list[ExerciseGroupModel] | None]
    calories: NotRequired[int | None]
    bpm: NotRequired[int | None]
    distance: NotRequired[float | None]
    climb: NotRequired[int | None]
    descent: NotRequired[float | None]
    bpm_avg: NotRequired[int | None]
    bpm_max: NotRequired[int | None]
    cadence_avg: NotRequired[int | None]
    cadence_max: NotRequired[int | None]
    power_avg: NotRequired[int | None]
    power_max: NotRequired[int | None]
    speed_avg: NotRequired[float | None]
    speed_max: NotRequired[float | None]
    pool_length: NotRequired[float | None]
    duplicate: NotRequired[bool]
    lang: NotRequired[str]
    status: NotRequired[TrainingStatus]
    id: str
    exercises: NotRequired[list[SessionExerciseModel] | None]



class PostMeasurementResp(TypedDict):
    measurement: MeasurementResp



class UserGetResp(TypedDict):
    user: UserResp
